name: Build and Test

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  regular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update packages list
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y build-essential libtool autoconf automake

      - name: Configure
        run: ./configure

      - name: Make
        run: |
          make

      - name: Test
        run: |
          make testprog
          ./testprog > testprog.lis
          diff testprog.lis testprog.out
          cmp testprog.fit testprog.std

      - name: Cookbook
        run: |
          ./cookbook

      - name: Speed
        run: |
          ./speed

#      - name: Iterators
#        run: |
#          ./iter_a
#          ./iter_b
#          ./iter_c
#          ./iter_var
#          ./iter_image

