name: Build and Test

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-on-linux-x64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update packages list
        run: sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install -y build-essential libtool autoconf automake

      - name: Configure
        run: ./configure

      - name: Make without reentrant
        run: |
          make

      - name: Test
        run: |
          make testprog
          ./testprog > testprog.lis
          diff testprog.lis testprog.out
          cmp testprog.fit testprog.std

      - name: Cookbook
        run: |
          ./cookbook > cookbook.lis
          diff cookbook.lis cookbook.out

      - name: Speed
        run: |
          ./speed

      - name: Make with reentrant
        run: |
          make clean
          ./configure --enable-reentrant
          make

#      - name: Iterators
#        run: |
#          ./iter_a
#          ./iter_b
#          ./iter_c
#          ./iter_var
#          ./iter_image

